version: '3'
services:
 rest-level2:
  image: node:latest
  container_name: serverA
  ports:
   - "80:8080"
  command: ["bin/bash"]
  volumes:
   - ./:/code
  depends_on:
   - couchdb1 
  stdin_open: true
  tty: true
  
 rest-level3:
    image: node:latest
    container_name: serverB
    ports:
    - "81:8080"
    command: ["bin/bash"]
    volumes:
    - ./:/code
    depends_on:
    - couchdb1 
    stdin_open: true
    tty: true

 couchdb1:
    image: couchdb:3.2.0
    container_name: cdb1
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
        - ./database/couchdb:/opt/couchdb/data
    stdin_open: true
    tty: true    